export const TOGGLE_LOGIN = 'TOGGLE_LOGIN' // 登录页面开关
export const TOGGLE_SET_DRAWER = 'TOGGLE_SET_DRAWER' // 侧栏抽屉的开关
export const CHANGE_HEADER_TITLE = 'CHANGE_HEADER_TITLE' // 改变导航标题
export const TOGGLE_HISTORY = 'TOGGLE_HISTORY' // 历史记录的开关
export const TOGGLE_OFFLINE = 'TOGGLE_OFFLINE' // 离线缓存的开关
export const TOGGLE_MY_COLLECTION = 'TOGGLE_MY_COLLECTION'
export const TOGGLE_SIGN_UP = 'TOGGLE_SIGN_UP' // 关闭注册账号页面
export const HAS_LOGIN_IN = 'HAS_LOGIN_IN' // 已登录状态
export const TOGGLE_SET_UP = 'TOGGLE_SET_UP' // 设置页面开关
export const REFRESH_AJAX = 'REFRESH_AJAX' // 刷新请求
export const RECEVIVE_DATA = 'RECEVIVE_DATA' // 接收数据
export const VIDEO_RECOMMENDDATA = 'VIDEO_RECOMMENDDATA' // 推荐列表
export const RECEVIVE_VIDEO_DATA = 'RECEVIVE_VIDEO_DATA' // 接收每个视频信息
export const GET_ZONE_DATA = 'GET_ZONE_DATA' // 得到对应分区数据
export const TOGGLE_CHANNEL_LIST = 'TOGGLE_CHANNEL_LIST' // 展示频道列表
export const GET_CHANNEL_LIST = 'GET_CHANNEL_LIST' // 得到对应的分类列表
export const TOGGLE_SHOW_SHARE = 'TOGGLE_SHOW_SHARE'
export const USER_FAVORITE_DATA = 'USER_FAVORITE_DATA' // 用户收藏数据
export const CANCEL_FAVORITE_ITEM = 'CANCEL_FAVORITE_ITEM' // 取消收藏
export const GET_HISTORY_DATA = 'GET_HISTORY_DATA' // 得到历史记录
export const CHEAR_HISTORY = 'CHEAR_HISTORY' // 清除历史记录
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH' // 显示隐藏搜索页面
export const TOGGLE_PUBLIC = 'TOGGLE_PUBLIC'
export const SET_DRAWER_DATA = 'SET_DRAWER_DATA'
